project:
	tuist clean
	tuist install
	tuist generate --no-open && pod install &&  open HaruhanjulWorkspace.xcworkspace
	
open:
	tuist generate --no-open && pod install &&  open HaruhanjulWorkspace.xcworkspace

asset:
	tuist generate
	pod install
